---
title: "nonlinearspikeslabMCMCp5000"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(nonlinearspikeslab)
library(nimble)
library(tidyverse)
```

```{r}
source("Simul_donnees_Marion.R") #ATTENTION : bien vérifié que p=5000 dans ce fichier
```

```{r}
PlotSimulatedData(data_input, maxspecies = 30)
```


```{r}
nu_0 = 0.001

#set.seed(1)
#mcmc_out=FitOneVariableParamSpikeAndSlabDelay_marginal_delta_slow(data = data_input, nu_0 = nu_0, niter = 10000)
#save(mcmc_out,file="Test_MCMC_p5000_2.Rdata")

#load("Test_MCMC_p5000.Rdata") #nu_0=0.01
load("Test_MCMC_p5000_2.Rdata") #nu_0=0.001
```


```{r}
traceplot(mcmc.out = mcmc_out, parnames = c("Gamma2", "sigma2")) + scale_y_log10()
```

```{r}
PriorPosteriorPlotSmallVectorParams(mcmc_out = mcmc_out, parnames = c("sigma2", "Gamma2")) + scale_x_log10()
```

```{r}
CorrelationPlot(mcmc_out = mcmc_out, parnames = c("Gamma2", "sigma2"))
```


```{r}
traceplot(mcmc.out = mcmc_out, parnames = c("psi"))
```
```{r}
PriorPosteriorPlotSmallVectorParams(mcmc_out = mcmc_out, parnames = c("psi"))
```

```{r}
traceplot(mcmc.out = mcmc_out, parnames = c("alpha"))
```

```{r}
# PriorPosteriorPlotSmallVectorParams(mcmc_out = mcmc_out_marginal_delta, parnames = c("eta", "alpha"))
PriorPosteriorPlotSmallVectorParams(mcmc_out = mcmc_out, parnames = c("alpha"))
```

```{r}
traceplot(mcmc.out = mcmc_out, parnames = c("mu"))
```

```{r}
# PriorPosteriorPlotSmallVectorParams(mcmc_out = mcmc_out_marginal_delta, parnames = c("eta", "alpha"))
PriorPosteriorPlotSmallVectorParams(mcmc_out = mcmc_out, parnames = c("mu"))
```

```{r}
traceplot(mcmc.out = mcmc_out, parnames = c("beta[1]", "beta[2]", "beta[3]", "beta[4]", "beta[5]", "beta[6]"))
```
```{r}
traceplot(mcmc.out = mcmc_out,parnames = paste("phi[", 1:9, "]", sep = ""))
```

```{r}
#PriorPosteriorPlotSmallVectorParams(mcmc_out = mcmc_out, parnames = c("beta"))
```

```{r}
# PriorPosteriorPlotSmallVectorParams(mcmc_out = mcmc_out_marginal_delta, parnames = c("mu", "sigma2", "Gamma2", "psi")) + scale_x_log10()
```
```{r}
posterior_predictive_estimate(data = data_input, mcmc_out = mcmc_out, maxspecies = 20)
```
